apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
  type: NodePort
